---
- name: Deploy application container
  hosts: vostro-server
  remote_user: strange-loop-server

  tasks:
    - name: Check if image already exists and delete
      docker_image:
        name: strangeloop1710/react-calc
        state: absent
        force_absent: yes

    - name: Prune all images and containers
      docker_prune:
        containers: yes
        images: yes

    - name: Pull latest image
      docker_image:
        name: strangeloop1710/react-calc
        source: pull

    - name: Running application
      docker_container:
        name: react-calc
        image: strangeloop1710/react-calc
        state: started
        restart: yes
        ports:
          - "80:80"
