---
- name: Deploy application container
  hosts: vostro-server
  remote_user: strange-loop-server

  tasks:
    - name: Pull application image
      docker_image:
        name: strangeloop1710/react-calc
        source: pull

    - name: Running application
      docker_container:
        name: react-calc
        image: strangeloop1710/react-calc
        state: started
        ports:
          - "80:80"
